SELECT dpt.DEPARTMENT_ID
	,dpt.DEPARTMENT_NAME
	,loc.LOC_NAME
	,dpt.*
FROM CLARITY_DEP dpt
INNER JOIN CLARITY_LOC loc ON loc.LOC_ID = dpt.REV_LOC_ID
WHERE (
		loc.RECORD_STATUS IS NULL
		OR loc.RECORD_STATUS = '1'
		)
ORDER BY REV_LOC_ID
	,dpt.DEPARTMENT_ID
