SELECT dpt.DEPARTMENT_ID
	,dpt.DEPARTMENT_NAME
	,loc.LOC_NAME
	,dpt.*
FROM CLARITY_DEP dpt
INNER JOIN CLARITY_LOC loc ON loc.LOC_ID = dpt.REV_LOC_ID
WHERE (
		loc.RECORD_STATUS IS NULL
		OR loc.RECORD_STATUS = '1'
		)
	AND dpt.DEPARTMENT_NAME LIKE '%CH6%'
	OR dpt.DEPARTMENT_NAME LIKE '%CH7%'